# ---------------------------------------------------------------- figures / tables
def make_city_maps(city, G, data, res, out):
    import matplotlib.pyplot as plt
    last = res["results"][-1]
    panels = [("Labels (flooded cells)", data["flooded"].to_numpy(), "Blues"),
              (f"Physical OOF risk ({last['rung']})", last["scores"]["physical"], "viridis"),
              ("Social layer: log1p mentions/km²", data["S_mentions"].to_numpy(), "magma")]
    fig, axes = plt.subplots(1, 3, figsize=(10.5, 3.6))
    for ax, (title, vals, cmap) in zip(axes, panels):
        ras = ph.cells_to_raster(vals, data, G)
        im = ax.imshow(ras, cmap=cmap, interpolation="nearest")
        ax.set_title(title, fontsize=8)
        ax.set_xticks([]); ax.set_yticks([])
        fig.colorbar(im, ax=ax, fraction=0.046, pad=0.02)
    fig.suptitle(f"{city} — 100 m grid ({G.crs})", fontsize=9)
    fig.tight_layout()
    fig.savefig(os.path.join(out, "fig_maps.png"), dpi=250)
    fig.savefig(os.path.join(out, "fig_maps.pdf"))
    plt.close(fig)


def write_report(city_results, prereg, profile, out_root, log):
    import matplotlib.pyplot as plt
    P = PROFILES[profile]
    ok = [r for r in city_results if r.get("results")]
    macros = [f"% Auto-generated by saturation pipeline {PIPELINE_VERSION}. Do not edit by hand.",
              f"% profile: {P['label']}", f"% generated {dt.datetime.utcnow().isoformat()}Z"]
    rows = []
    if ok:
        fig, axes = plt.subplots(len(ok), 2, figsize=(7.4, 3.0 * len(ok)), squeeze=False)
    for i, r in enumerate(ok):
        cc = city_code(r["city"])
        macros.append(sc.latex_macros(cc, {"Cells": r["prov"]["n_cells"], "Positives": r["positives"], "Prevalence": r["prevalence"],
                                           "LabelSource": r["label_source"], "Mentions": r["social"].get("mentions", 0),
                                           "SignalCells": r["social"].get("cells_with_signal", 0)}, nd=4))
        for j, (ordering, res) in enumerate(r["results"].items()):
            oc = ordering[0]
            s, g_all = res["summary"], res["gradient"]
            # primary/secondary rows are unique per metric; robustness rows repeat metric names, so keep them apart
            g = g_all[g_all["role"] != "robust_excl_R0"].set_index("metric")
            g_rob = g_all[g_all["role"] == "robust_excl_R0"].set_index("metric")
            ax = axes[i, j]
            # primary axes: per-fold physical skill vs per-fold, null-centred social gain
            xk = "AP_recal_fm" if "AP_recal_fm" in s else "AP_recal"
            yk = "dAP_stacked_fm_adj" if "dAP_stacked_fm_adj" in s else "dAPh_stacked"
            bk = yk[:-4] if yk.endswith("_adj") else yk
            x, yv = s[xk], s[yk]
            ylo = s.get(f"{bk}_lo"); yhi = s.get(f"{bk}_hi"); xlo = s.get(f"{xk}_lo"); xhi = s.get(f"{xk}_hi")
            shift = (s[bk] - s[yk]) if yk.endswith("_adj") else 0.0
            kw = {}
            if ylo is not None and yhi is not None:
                kw["yerr"] = [(yv - (ylo - shift)).clip(lower=0), ((yhi - shift) - yv).clip(lower=0)]
            if xlo is not None and xhi is not None:
                kw["xerr"] = [(x - xlo).clip(lower=0), (xhi - x).clip(lower=0)]
            ax.errorbar(x, yv, fmt="o-", ms=3, lw=1, capsize=2, label="stacked (R,S), null-centred", **kw)
            if "dAP_early_fm_adj" in s:
                ax.plot(x, s["dAP_early_fm_adj"], "^:", ms=3, lw=1, label="early fusion, null-centred")
            ax.plot(x, s.get("dAP_gated_fm", s["dAP_gated"]), "s--", ms=3, lw=1, label="gated, corrected")
            ax.axhline(0, color="k", lw=0.6)
            for xx, yy, rn in zip(x, yv, s["rung"]):
                ax.annotate(rn.split("_")[0], (xx, yy), fontsize=6, xytext=(2, 2), textcoords="offset points")
            ax.set_title(f"{r['city']} — ordering {oc}", fontsize=9)
            ax.set_xlabel("held-out physical AP (per-fold mean)")
            ax.set_ylabel("ΔAP from the social layer\n(per-fold, minus spatial-null mean)")
            if i == 0 and j == 0:
                ax.legend(fontsize=7)
            def gval(metric, field, default=np.nan):
                return g.loc[metric, field] if metric in g.index else default
            macros.append(sc.latex_macros(f"{cc}{oc}Slope", {
                # primary (per-fold, null-centred)
                "Stacked": gval("dAP_stacked_fm_adj", "slope"), "StackedLo": gval("dAP_stacked_fm_adj", "slope_ci_low"),
                "StackedHi": gval("dAP_stacked_fm_adj", "slope_ci_high"),
                "StackedP": gval("dAP_stacked_fm_adj", "p_one_sided_slope_ge_0"),
                "Info": gval("info_nats_fm_adj", "slope"), "InfoLo": gval("info_nats_fm_adj", "slope_ci_low"),
                "InfoHi": gval("info_nats_fm_adj", "slope_ci_high"),
                "InfoP": gval("info_nats_fm_adj", "p_one_sided_slope_ge_0"),
                "Early": gval("dAP_early_fm_adj", "slope"), "EarlyP": gval("dAP_early_fm_adj", "p_one_sided_slope_ge_0"),
                # secondary (pooled; the headroom denominator amplifies late rungs)
                "PooledInfo": gval("info_nats", "slope"), "PooledInfoP": gval("info_nats", "p_one_sided_slope_ge_0"),
                "Headroom": gval("dAPh_stacked", "slope"), "HeadroomP": gval("dAPh_stacked", "p_one_sided_slope_ge_0"),
                # robustness: primary gradients without the empty-model rung R0
                "StackedExclRzero": g_rob.loc["dAP_stacked_fm_adj", "slope"] if "dAP_stacked_fm_adj" in g_rob.index else np.nan,
                "StackedExclRzeroHi": g_rob.loc["dAP_stacked_fm_adj", "slope_ci_high"] if "dAP_stacked_fm_adj" in g_rob.index else np.nan,
                "InfoExclRzero": g_rob.loc["info_nats_fm_adj", "slope"] if "info_nats_fm_adj" in g_rob.index else np.nan,
                "InfoExclRzeroHi": g_rob.loc["info_nats_fm_adj", "slope_ci_high"] if "info_nats_fm_adj" in g_rob.index else np.nan}))
            for _, row in s.iterrows():
                rid = row["rung"].split("_")[0]
                macros.append(sc.latex_macros(f"{cc}{oc}{rid}", {
                    # primary: per-fold, null-centred
                    "APphys": row.get("AP_recal_fm", row["AP_recal"]), "APphysSd": row.get("AP_recal_fm_sd", np.nan),
                    "APstacked": row.get("AP_stacked_fm", row["AP_stacked"]),
                    "Info": row.get("info_nats_fm_adj", np.nan), "InfoRaw": row.get("info_nats_fm", np.nan),
                    "InfoNullMean": row.get("null_mean_info_nats_fm", np.nan),
                    "InfoP": row.get("p_null_info_nats_fm", row.get("p_null_info_nats", np.nan)),
                    "dAPstacked": row.get("dAP_stacked_fm_adj", np.nan),
                    "dAPearly": row.get("dAP_early_fm_adj", np.nan),
                    "dAPearlyNullMean": row.get("null_mean_dAP_early_fm", np.nan),
                    "dAPearlyP": row.get("p_null_dAP_early_fm", row.get("p_null_dAP_early", np.nan)),
                    "dAPgated": row.get("dAP_gated_fm", row["dAP_gated"]),
                    "dAPlegacy": row.get("dAP_adr_legacy_fm", row.get("dAP_adr_legacy", np.nan)),
                    # secondary: pooled
                    "APphysPooled": row["AP_recal"], "APphysPooledLo": row["AP_recal_lo"],
                    "APphysPooledHi": row["AP_recal_hi"], "InfoPooled": row["info_nats"],
                    "dAPh": row["dAPh_stacked"], "dAPhLo": row["dAPh_stacked_lo"], "dAPhHi": row["dAPh_stacked_hi"]}))
                rows.append(dict(city=r["city"], gt_tier=r.get("gt_tier"), ordering=ordering, **row.to_dict()))
            pick = [("rung", "Rung"), ("n_features", "$k$"),
                    ("AP_recal_fm", "AP$_R$ (fold)"), ("AP_recal_fm_sd", "sd"),
                    ("info_nats_fm_adj", r"$\hat I^{\mathrm{adj}}$ (nats)"),
                    ("p_null_info_nats_fm", r"$p_{\mathrm{null}}$"),
                    ("dAP_stacked_fm_adj", r"$\Delta$AP stacked$^{\mathrm{adj}}$"),
                    ("dAP_early_fm_adj", r"$\Delta$AP early$^{\mathrm{adj}}$"),
                    ("p_null_dAP_early_fm", r"$p_{\mathrm{early}}$"),
                    ("dAP_gated_fm", r"$\Delta$AP gated"), ("dAP_adr_legacy_fm", r"$\Delta$AP legacy"),
                    ("dAPh_stacked", r"$\Delta$AP$_h$ (pooled)")]
            pick = [(c, n) for c, n in pick if c in s.columns]
            tab = s[[c for c, _ in pick]].copy()
            tab.columns = [n for _, n in pick]
            tab["Rung"] = tab["Rung"].str.replace("_", r"\_", regex=False)
            with open(os.path.join(out_root, f"table_{cc}{oc}.tex"), "w") as fh:
                fh.write(tab.to_latex(index=False, escape=False, float_format=lambda v: sc.fmt_num(v, 3)))
        if r["lens"]:
            lens = pd.concat(r["lens"])
            fig2, ax2 = plt.subplots(figsize=(6.5, 0.35 * len(lens) + 1.2))
            ik = "info_nats_fm_adj" if "info_nats_fm_adj" in lens.columns else "info_nats"
            bk = ik[:-4] if ik.endswith("_adj") else ik
            shift = (lens[bk] - lens[ik]) if ik.endswith("_adj") else 0.0
            xe = None
            if f"{bk}_lo" in lens.columns and f"{bk}_hi" in lens.columns:
                xe = [(lens[ik] - (lens[f"{bk}_lo"] - shift)).clip(lower=0),
                      ((lens[f"{bk}_hi"] - shift) - lens[ik]).clip(lower=0)]
            ax2.barh(lens["channel"], lens[ik], xerr=xe, capsize=2)
            ax2.axvline(0, color="k", lw=0.6)
            ax2.set_xlabel("information gain Î (nats), per-fold and null-centred  [most complete rung]")
            ax2.set_title(f"{r['city']} — emotion/social channels", fontsize=9)
            fig2.tight_layout(); fig2.savefig(os.path.join(out_root, f"fig_emotion_lens_{cc}.png"), dpi=250)
            fig2.savefig(os.path.join(out_root, f"fig_emotion_lens_{cc}.pdf")); plt.close(fig2)
    if ok:
        fig.tight_layout(); fig.savefig(os.path.join(out_root, "fig_saturation_curves.png"), dpi=300)
        fig.savefig(os.path.join(out_root, "fig_saturation_curves.pdf")); plt.close(fig)
    open(os.path.join(out_root, "results_macros.tex"), "w").write("\n".join(macros) + "\n")
    pd.DataFrame(rows).to_csv(os.path.join(out_root, "all_cities_summary.csv"), index=False)
    overview = pd.DataFrame([dict(city=r["city"], status="ok" if r.get("results") else "failed",
                                  label_source=r.get("effective_label_source") or r.get("label_source"),
                                  gt_tier=r.get("gt_tier"),
                                  confirmatory=r.get("gt_tier") == "A_authoritative",
                                  positives=r.get("positives"), cells_analysed=r.get("cells_analysed"),
                                  prevalence=r.get("prevalence"), mentions=(r.get("social") or {}).get("mentions"),
                                  prereg_sha256=str(r.get("prereg_sha256") or "")[:8],
                                  pipeline_version=r.get("pipeline_version") or PIPELINE_VERSION,
                                  from_earlier_session=bool(r.get("from_earlier_session", False)),
                                  error=r.get("error", "")) for r in city_results])
    overview.to_csv(os.path.join(out_root, "cities_overview.csv"), index=False)
    return overview


# ---------------------------------------------------------------- v5.5 cross-city synthesis (RQ1-RQ3)
SYN_DIR = "paper_synthesis"
# v6 design: every tier-A city is confirmatory; localisation (label-free) is the pre-registered moderator, and
# the localisable subset is a conditional secondary set (reported whatever its size)
CONFIRMATORY = "tier A, all (confirmatory)"
LOCALISABLE = "tier A, localisable (conditional)"
EVALUABLE = "tier A, evaluable social layer (sensitivity, added in v6.1)"
MIN_EVALUABLE_MENTIONS = 10       # = social.min_source_mentions and the "sparse social layer" warning since v5
CO_PRIMARY = ["info_nats_fm_adj", "dAP_stacked_fm_adj"]
NORMALISED = ["info_frac_fm_adj", "dAPh_fm_adj"]
TOP_METRICS = ["info_frac_fm", "dAP_stacked_fm", "dAP_gated_fm", "dAP_early_fm", "dAP_adr_legacy_fm"]


def _slope_rows(states, ordering, role, metrics, tag="results"):
    rows = []
    for c, st_ in states.items():
        src = (st_.get("placebo") or {}) if tag == "placebo" else (st_.get("results") or {}).get(ordering)
        if not src or src.get("gradient") is None:
            continue
        g = src["gradient"]
        for m in metrics:
            gg = g[(g["role"] == role) & (g["metric"] == m)]
            if gg.empty:
                continue
            r = gg.iloc[0]
            se = r.get("slope_se", np.nan)
            if not np.isfinite(se):
                se = (r["slope_ci_high"] - r["slope_ci_low"]) / 3.92
            rows.append(dict(city=c, ordering=ordering, role=role, metric=m, slope=r["slope"], se=se,
                             ci_low=r["slope_ci_low"], ci_high=r["slope_ci_high"],
                             p_one_sided=r["p_one_sided_slope_ge_0"], n_rungs=r["n_rungs"]))
    return pd.DataFrame(rows)


def _city_sets(states, h, prereg=None):
    """Pooled sets. v6.1: (1) only cities of the pre-registered study set are pooled (if one is declared), so a
    report state left in the output folder by another run cannot enter a pooled estimate unnoticed; (2) the
    'evaluable' sensitivity set drops tier-A cities whose social layer has too few located mentions to evaluate."""
    ap_ = (prereg or {}).get("analysis_plan") or {}
    study = set(ap_.get("study_set") or [])
    info = {}
    for c, st_ in states.items():
        prov = st_.get("prov") or {}
        loc = prov.get("localisation") or {}
        ev = prov.get("evaluable_social_layer")
        if ev is None:
            ev = int(loc.get("n_mentions") or 0) >= int(ap_.get("min_evaluable_mentions", MIN_EVALUABLE_MENTIONS))
        info[c] = dict(current=st_.get("prereg_sha256") == h, tier=st_.get("gt_tier"),
                       eligible=bool(loc.get("eligible", False)), evaluable=bool(ev),
                       in_study=(c in study) if study else True,
                       acquisition_complete=bool((prov.get("acquisition_status") or {}).get("complete", False)))
    cur = {c for c, v in info.items() if v["current"] and v["in_study"]}
    sets = {
        CONFIRMATORY: {c for c in cur if info[c]["tier"] == "A_authoritative"},
        EVALUABLE: {c for c in cur if info[c]["tier"] == "A_authoritative" and info[c]["evaluable"]},
        LOCALISABLE: {c for c in cur if info[c]["tier"] == "A_authoritative" and info[c]["eligible"]},
        "tier A + A-points": {c for c in cur if str(info[c]["tier"]).startswith("A_")},
        "tier A + A-points, localisable": {c for c in cur if str(info[c]["tier"]).startswith("A_") and info[c]["eligible"]},
        "all localisable (any tier)": {c for c in cur if info[c]["eligible"]},
    }
    return info, sets


def write_synthesis(states, prereg, h, out_root, log):
    import matplotlib.pyplot as plt
    ap_ = prereg.get("analysis_plan") or {}
    d = os.path.join(out_root, SYN_DIR)
    os.makedirs(d, exist_ok=True)
    info, sets = _city_sets(states, h, prereg)
    stale = sorted(c for c, v in info.items() if not v["current"])
    outside = sorted(c for c, v in info.items() if not v["in_study"])
    sesoi_ap = float(((ap_.get("sesoi") or {}).get("dAP_stacked_fm")) or sc.SESOI["dAP_stacked_fm"])
    # ---- T1: city characteristics ----------------------------------------------------------------------
    t1 = []
    for c, st_ in sorted(states.items()):
        prov = st_.get("prov") or {}
        loc = prov.get("localisation") or {}
        sA = ((st_.get("results") or {}).get("A_terrain_first") or {}).get("summary")
        top = sA.iloc[-1] if sA is not None and len(sA) else None
        t1.append(dict(city=c, current_prereg=info[c]["current"], gt_tier=st_.get("gt_tier"),
                       label_source=st_.get("effective_label_source") or st_.get("label_source"),
                       grid_m=prov.get("grid_m"), cells_analysed=st_.get("cells_analysed"), positives=st_.get("positives"),
                       prevalence=st_.get("prevalence"), top_rung=None if top is None else top["rung"],
                       AP_top_fm=None if top is None else top.get("AP_recal_fm"),
                       lift_top=None if top is None or not st_.get("prevalence") else top.get("AP_recal_fm") / st_["prevalence"],
                       mentions_primary=loc.get("n_mentions"), effective_locations=loc.get("effective_locations"),
                       top_place=loc.get("top_place"), top_place_share=loc.get("top_share"), localisable=loc.get("eligible"),
                       label_corr_range_m=prov.get("label_corr_range_m"),
                       gazetteer_source=(prov.get("gazetteer") or {}).get("source"),
                       gazetteer_names=(prov.get("gazetteer") or {}).get("names"),
                       social_population_spearman=prov.get("social_population_spearman"),
                       saturation_rung_A=prov.get("saturation_rung_A_terrain_first"),
                       in_study_set=info[c]["in_study"], evaluable_social_layer=info[c]["evaluable"],
                       signal_type=(prov.get("signal_primary") or {}).get("signal_type"),
                       share_news=((prov.get("signal_primary") or {}).get("shares") or {}).get("news"),
                       acquisition_complete=info[c]["acquisition_complete"],
                       label_caveat=prov.get("label_caveat")))
    T1 = pd.DataFrame(t1)
    T1.to_csv(os.path.join(d, "T1_city_characteristics.csv"), index=False)
    # ---- RQ2: per-city gradients + Holm; RQ3: random-effects meta-analysis ------------------------------------
    per_city, meta_rows = [], []
    for ordering in ("A_terrain_first", "B_surface_first"):
        for role, mets in (("primary", CO_PRIMARY), ("robust_excl_R0", CO_PRIMARY),
                           ("headroom_normalised", NORMALISED), ("headroom_normalised_excl_R0", NORMALISED)):
            sr = _slope_rows(states, ordering, role, mets)
            if sr.empty:
                continue
            per_city.append(sr)
            for set_name, members in sets.items():
                for m in mets:
                    x = sr[(sr["metric"] == m) & sr["city"].isin(members)]
                    ma = sc.meta_analysis(x["slope"], x["se"])
                    meta_rows.append(dict(set=set_name, ordering=ordering, role=role, metric=m,
                                          cities=",".join(sorted(x["city"])), **ma))
    PC = pd.concat(per_city, ignore_index=True) if per_city else pd.DataFrame()
    if len(PC):
        prim = sets[CONFIRMATORY]
        fam = (PC["ordering"] == "A_terrain_first") & (PC["role"] == "primary") & PC["city"].isin(prim) & PC["metric"].isin(CO_PRIMARY)
        PC["holm_p_primary_family"] = np.nan
        PC.loc[fam, "holm_p_primary_family"] = sc.holm(PC.loc[fam, "p_one_sided"].to_numpy())
        PC["in_confirmatory_set"] = PC["city"].isin(prim)
        PC["localisable"] = PC["city"].isin(sets[LOCALISABLE])
    PC.to_csv(os.path.join(d, "T2_per_city_gradients.csv"), index=False)
    META = pd.DataFrame(meta_rows)
    META.to_csv(os.path.join(d, "T3_meta_gradients.csv"), index=False)
    # ---- RQ1: operators at the most complete rung ----------------------------------------------------------
    top_rows, top_meta = [], []
    for c, st_ in states.items():
        e = ((st_.get("results") or {}).get("A_terrain_first") or {}).get("effects")
        if e is None or not len(e):
            continue
        last = e[e["rung"] == e["rung"].iloc[-1]]
        for r in last.itertuples():
            d_ = r.sesoi if np.isfinite(r.sesoi) else None
            within = getattr(r, "within_sesoi", None)
            if within is None:          # report states written before v6.1
                within = bool(d_ is not None and np.isfinite(r.ci90_low) and -d_ < r.ci90_low and r.ci90_high < d_)
            reading = getattr(r, "reading", None) or (
                "negligible (non-zero but within SESOI)" if within and r.verdict in ("informative", "harmful")
                else "equivalent to zero (within SESOI)" if within else r.verdict)
            top_rows.append(dict(city=c, rung=r.rung, metric=r.metric, estimate=r.estimate, ci90_low=r.ci90_low,
                                 ci90_high=r.ci90_high, ci95_low=r.ci95_low, ci95_high=r.ci95_high, p_null=r.p_null,
                                 sesoi=r.sesoi, verdict=r.verdict, within_sesoi=bool(within), reading=reading,
                                 evaluable_social_layer=info[c]["evaluable"], se=(r.ci95_high - r.ci95_low) / 3.92))
    TOP = pd.DataFrame(top_rows)
    TOP.to_csv(os.path.join(d, "T4_top_rung_effects.csv"), index=False)
    for set_name, members in sets.items():
        for m in TOP_METRICS:
            x = TOP[(TOP["metric"] == m) & TOP["city"].isin(members)] if len(TOP) else TOP
            if len(x):
                top_meta.append(dict(set=set_name, metric=m, cities=",".join(sorted(x["city"])),
                                     **sc.meta_analysis(x["estimate"], x["se"])))
    TM = pd.DataFrame(top_meta)
    TM.to_csv(os.path.join(d, "T5_meta_top_rung.csv"), index=False)
    # ---- negative control: population-density placebo ----------------------------------------------------------
    pl_rows = []
    for c, st_ in states.items():
        pl = st_.get("placebo")
        if not pl:
            continue
        real = _slope_rows({c: st_}, "A_terrain_first", "primary", CO_PRIMARY)
        fake = _slope_rows({c: st_}, "A_terrain_first", "primary", CO_PRIMARY, tag="placebo")
        ce = pl.get("control_effects")
        for m in CO_PRIMARY:
            a = real[real["metric"] == m]
            b = fake[fake["metric"] == m]
            if a.empty or b.empty:
                continue
            row = dict(city=c, metric=m, real_slope=a["slope"].iloc[0], real_se=a["se"].iloc[0],
                       placebo_slope=b["slope"].iloc[0], placebo_se=b["se"].iloc[0],
                       spearman_social_population=pl.get("spearman_social_pop"))
            row["difference"] = row["real_slope"] - row["placebo_slope"]
            row["difference_se_approx"] = float(np.hypot(row["real_se"], row["placebo_se"]))
            if ce is not None and len(ce):
                cm = ce[ce["metric"] == ("info_frac_fm" if m.startswith("info") else "dAP_stacked_fm")]
                if len(cm):
                    row.update(control_top_estimate=cm["estimate"].iloc[0], control_top_ci95_low=cm["ci95_low"].iloc[0],
                               control_top_ci95_high=cm["ci95_high"].iloc[0], control_top_verdict=cm["verdict"].iloc[0])
            pl_rows.append(row)
    PL = pd.DataFrame(pl_rows)
    PL.to_csv(os.path.join(d, "T6_density_placebo.csv"), index=False)
    pl_meta = []
    for set_name, members in sets.items():
        for m in CO_PRIMARY:
            x = PL[(PL["metric"] == m) & PL["city"].isin(members)] if len(PL) else PL
            if len(x):
                pl_meta.append(dict(set=set_name, metric=m, quantity="placebo slope", **sc.meta_analysis(x["placebo_slope"], x["placebo_se"])))
                pl_meta.append(dict(set=set_name, metric=m, quantity="real minus placebo slope",
                                    **sc.meta_analysis(x["difference"], x["difference_se_approx"])))
    pd.DataFrame(pl_meta).to_csv(os.path.join(d, "T7_meta_density_placebo.csv"), index=False)
    # ---- RQ3 moderator (confirmatory, v6): localisation of the social layer ---------------------------------------
    # label-free moderator = log effective number of mention locations in the primary window; outcomes = the per-city
    # gradient slopes (co-primary) and the top-rung effects (RQ1 metrics); confirmatory set only
    mod_rows = []
    conf = sets[CONFIRMATORY]
    if len(T1):
        loc = T1.set_index("city")
        logeff = lambda cities: np.log(pd.to_numeric(loc.reindex(cities)["effective_locations"], errors="coerce").clip(lower=1.0))

        def _mod(analysis, outcome, x, ycol, modname="log_effective_locations", vals=None, influence=False):
            xv = logeff(x["city"]).to_numpy() if vals is None else np.asarray(vals, float)
            row = dict(analysis=analysis, outcome=outcome, moderator=modname, cities=",".join(sorted(x["city"])),
                       **sc.meta_regression(x[ycol], x["se"], xv))
            if influence:
                row.update(sc.metareg_influence(x[ycol], x["se"], xv, x["city"]))
            mod_rows.append(row)
        # the evaluable set repeats the confirmatory tests without the cities that have no usable social layer
        # (v6.1, added after the v6.0 results were seen: a sensitivity analysis, never the headline)
        for analysis, members, infl in (("confirmatory", conf, True),
                                        ("sensitivity: evaluable social layer", sets[EVALUABLE], False)):
            if analysis != "confirmatory" and members == conf:
                continue
            if len(PC):
                base = PC[(PC["ordering"] == "A_terrain_first") & (PC["role"] == "primary") & PC["city"].isin(members)]
                for m in CO_PRIMARY:
                    _mod(analysis, f"gradient slope {m}", base[base["metric"] == m], "slope", influence=infl)
            if len(TOP):
                for m in TOP_METRICS:
                    _mod(analysis, f"top-rung {m}", TOP[(TOP["metric"] == m) & TOP["city"].isin(members)], "estimate",
                         influence=infl)
        if len(PC):
            base = PC[(PC["ordering"] == "A_terrain_first") & (PC["role"] == "primary")].merge(T1, on="city", how="left")
            for m in CO_PRIMARY:
                x = base[(base["metric"] == m) & base["city"].isin(conf)]
                for mod, vals in [("physical_lift_top_rung", pd.to_numeric(x["lift_top"], errors="coerce")),
                                  ("log_mentions", np.log(pd.to_numeric(x["mentions_primary"], errors="coerce").clip(lower=1)))]:
                    _mod("exploratory", f"gradient slope {m}", x, "slope", modname=mod, vals=vals.to_numpy())
    MOD = pd.DataFrame(mod_rows)
    if len(MOD):
        # v6.1: the confirmatory moderator is tested on several outcomes (2 slopes + 5 top-rung effects); v6.0
        # reported each permutation p on its own. Holm across that family, on the p-value that is reported
        # (permutation p for k < 10, as pre-registered).
        MOD["p_holm_family"] = np.nan
        fam = MOD["analysis"] == "confirmatory"
        MOD.loc[fam, "p_holm_family"] = sc.holm(MOD.loc[fam, "p_perm"].where(MOD.loc[fam, "p_perm"].notna(), MOD.loc[fam, "p"]).to_numpy())
        MOD["family_size"] = np.where(fam, int(fam.sum()), np.nan)
    MOD.to_csv(os.path.join(d, "T8_meta_regression_localisation.csv"), index=False)
    # ---- T11 (v6.1): who carries each pooled estimate (confirmatory set; weights and leave-one-out) -----------------
    infl = []
    if len(TOP):
        for m in TOP_METRICS:
            x = TOP[(TOP["metric"] == m) & TOP["city"].isin(conf)]
            if len(x) >= 3:
                infl.append(sc.meta_influence(x["estimate"], x["se"], x["city"]).assign(quantity=f"top-rung {m}"))
    if len(PC):
        base = PC[(PC["ordering"] == "A_terrain_first") & (PC["role"] == "primary") & PC["city"].isin(conf)]
        for m in CO_PRIMARY:
            x = base[base["metric"] == m]
            if len(x) >= 3:
                infl.append(sc.meta_influence(x["slope"], x["se"], x["city"]).assign(quantity=f"gradient slope {m}"))
    INFL = pd.concat(infl, ignore_index=True) if infl else pd.DataFrame()
    if len(INFL):
        INFL = INFL[["quantity"] + [c_ for c_ in INFL.columns if c_ != "quantity"]]
    INFL.to_csv(os.path.join(d, "T11_influence_leave_one_out.csv"), index=False)
    # ---- T9: localisation audit (label-free; every city) ---------------------------------------------------------------
    t9 = []
    for c, st_ in sorted(states.items()):
        prov = st_.get("prov") or {}
        loc_ = prov.get("localisation") or {}
        docs_ = prov.get("documents") or {}
        top_ = prov.get("toponyms") or {}
        t9.append(dict(city=c, gt_tier=st_.get("gt_tier"), documents_kept=docs_.get("kept_total"),
                       documents_by_source=json.dumps(docs_.get("kept_by_source", {}), sort_keys=True),
                       mentions_primary=loc_.get("n_mentions"), by_resolution=json.dumps(loc_.get("via", {}), sort_keys=True),
                       distinct_locations=loc_.get("distinct_locations"), effective_locations=loc_.get("effective_locations"),
                       top_place=loc_.get("top_place"), top_share=loc_.get("top_share"), top5=json.dumps(loc_.get("top5", [])),
                       localisable=loc_.get("eligible"), gazetteer_names=(prov.get("gazetteer") or {}).get("names"),
                       toponym_candidates_dropped=top_.get("dropped"),
                       signal_type=(prov.get("signal_primary") or {}).get("signal_type"),
                       mention_shares_by_kind=json.dumps((prov.get("signal_primary") or {}).get("shares", {}), sort_keys=True),
                       sources_switched_off=",".join(docs_.get("sources_switched_off", []) or []),
                       evaluable_social_layer=info[c]["evaluable"],
                       acquisition_rules=(prov.get("acquisition_status") or {}).get("rules"),
                       acquisition_complete=info[c]["acquisition_complete"],
                       acquisition_pending=" | ".join((prov.get("acquisition_status") or {}).get("pending", []) or []),
                       geocoder_calls=(prov.get("geocoding") or {}).get("geocoder_calls"),
                       lookups_not_done=(prov.get("geocoding") or {}).get("lookups_capped"),
                       ner_candidates_rejected=(prov.get("geocoding") or {}).get("ner_candidates_rejected")))
    pd.DataFrame(t9).to_csv(os.path.join(d, "T9_localisation_audit.csv"), index=False)
    # ---- T10: sensitivity roll-up (top rung, every variant incl. learner family) --------------------------------------
    t10 = []
    keep_cols = ["rung", "AP_recal_fm", "info_nats_fm_adj", "info_frac_fm_adj", "dAP_stacked_fm_adj", "dAP_gated_fm",
                 "dAP_early_fm_adj", "dAP_adr_legacy_fm", "variant", "gate_alpha_median", "gate_off_share"]
    for c, st_ in sorted(states.items()):
        for sdf in st_.get("sens") or []:
            if sdf is None or not len(sdf):
                continue
            x = sdf[[k_ for k_ in keep_cols if k_ in sdf.columns]].copy()
            x.insert(0, "city", c)
            # v6.1: how far each variant moves the co-primary top-rung effect, and whether it flips its sign by more
            # than the SESOI (Emilia-Romagna's -0.136 AP became +0.004 at the 1,000 m bandwidth in the v6.0 run)
            sA_ = ((st_.get("results") or {}).get("A_terrain_first") or {}).get("summary")
            if sA_ is not None and len(sA_) and "dAP_stacked_fm_adj" in sA_.columns and "dAP_stacked_fm_adj" in x.columns:
                prim_ = float(sA_["dAP_stacked_fm_adj"].iloc[-1])
                v_ = pd.to_numeric(x["dAP_stacked_fm_adj"], errors="coerce")
                x["primary_dAP_stacked_fm_adj"] = prim_
                x["delta_vs_primary"] = v_ - prim_
                x["unstable"] = ((np.sign(v_) != np.sign(prim_)) & ((v_ - prim_).abs() > sesoi_ap)) | ((v_ - prim_).abs() > 5 * sesoi_ap)
            t10.append(x)
    pd.concat(t10, ignore_index=True).to_csv(os.path.join(d, "T10_sensitivity_top_rung.csv"), index=False) if t10 else None
    # ---- forest plot (primary ordering, co-primary metrics) ------------------------------------------------------
    try:
        if len(PC):
            fig, axes = plt.subplots(1, 2, figsize=(9.0, 0.45 * max(4, PC["city"].nunique()) + 1.6), squeeze=False)
            prim = sets[CONFIRMATORY]
            for ax, m, lab in zip(axes[0], CO_PRIMARY, ["information gain (nats) per unit physical AP",
                                                        "ΔAP (stacked) per unit physical AP"]):
                x = PC[(PC["ordering"] == "A_terrain_first") & (PC["role"] == "primary") & (PC["metric"] == m)
                       & PC["city"].map(lambda c_: info.get(c_, {}).get("current", False))].sort_values("city")
                ys = np.arange(len(x))[::-1] + 1
                for yy, r in zip(ys, x.itertuples()):
                    filled = r.city in sets[LOCALISABLE]
                    ax.errorbar(r.slope, yy, xerr=[[max(0.0, r.slope - r.ci_low)], [max(0.0, r.ci_high - r.slope)]], fmt="o" if filled else "o",
                                mfc="k" if filled else "white", mec="k", ecolor="k", capsize=2, ms=4)
                mm = META[(META["set"] == CONFIRMATORY) & (META["ordering"] == "A_terrain_first")
                          & (META["role"] == "primary") & (META["metric"] == m)]
                if len(mm) and np.isfinite(mm["estimate"].iloc[0]):
                    e, lo_, hi_ = mm["estimate"].iloc[0], mm["ci_low"].iloc[0], mm["ci_high"].iloc[0]
                    if np.isfinite(lo_):
                        ax.fill([lo_, e, hi_, e], [0, 0.25, 0, -0.25], color="0.3")
                    else:
                        ax.plot([e], [0], "D", color="0.3")
                ax.axvline(0, color="k", lw=0.6, ls=":")
                ax.set_yticks(list(ys) + [0]); ax.set_yticklabels(list(x["city"]) + [f"pooled (k={int(mm['k'].iloc[0]) if len(mm) else 0})"], fontsize=7)
                ax.set_xlabel(f"gradient slope: {lab}", fontsize=8)
            fig.suptitle("Saturation gradient per city (ordering A; filled = localisable social layer; pooled = tier A, all; 95% CIs)", fontsize=9)
            fig.tight_layout()
            fig.savefig(os.path.join(d, "fig_forest_gradients.png"), dpi=300); fig.savefig(os.path.join(d, "fig_forest_gradients.pdf"))
            plt.close(fig)
    except Exception as e:  # noqa: BLE001
        log("(all)", "synthesis:figure", "warn", f"forest plot failed: {e}")
    # ---- LaTeX tables + macros ------------------------------------------------------------------------------------
    def tex(df, name, cols):
        cols = [c for c in cols if c in df.columns]
        if not len(df) or not cols:
            return
        t = df[cols].copy()
        for c in t.columns:
            if t[c].dtype == object:
                t[c] = t[c].astype(str).str.replace("_", r"\_", regex=False)
        with open(os.path.join(d, name), "w") as fh:
            fh.write(t.to_latex(index=False, escape=False, float_format=lambda v: sc.fmt_num(v, 3)))
    tex(T1, "T1_city_characteristics.tex", ["city", "gt_tier", "grid_m", "cells_analysed", "prevalence", "AP_top_fm",
                                            "lift_top", "mentions_primary", "effective_locations", "localisable"])
    tex(META[(META["ordering"] == "A_terrain_first")] if len(META) else META, "T3_meta_gradients.tex",
        ["set", "role", "metric", "k", "estimate", "ci_low", "ci_high", "p_one_sided_lt0", "tau2", "I2"])
    tex(TM, "T5_meta_top_rung.tex", ["set", "metric", "k", "estimate", "ci_low", "ci_high", "p_two_sided", "I2"])
    tex(MOD, "T8_meta_regression_localisation.tex", ["analysis", "outcome", "moderator", "k", "slope", "slope_se", "p", "p_perm",
                                                     "p_holm_family", "loo_slope_min", "loo_slope_max", "most_influential_city"])
    tex(INFL, "T11_influence_leave_one_out.tex", ["quantity", "city", "weight", "estimate", "loo_estimate", "loo_ci_low", "loo_ci_high"])
    macros = [f"% {PIPELINE_VERSION} synthesis, prereg {h[:8]}, generated {dt.datetime.utcnow().isoformat()}Z"]
    for r in (MOD[MOD["analysis"] == "confirmatory"].itertuples() if len(MOD) else []):
        mk = {"gradient slope info_nats_fm_adj": "GradInfo", "gradient slope dAP_stacked_fm_adj": "GradStacked",
              "top-rung info_frac_fm": "TopInfoFrac", "top-rung dAP_stacked_fm": "TopStacked", "top-rung dAP_gated_fm": "TopGated",
              "top-rung dAP_early_fm": "TopEarly", "top-rung dAP_adr_legacy_fm": "TopLegacy"}.get(r.outcome)
        if mk and np.isfinite(r.slope):
            macros.append(sc.latex_macros(f"ModLoc{mk}", {"K": int(r.k), "Slope": r.slope, "Se": r.slope_se, "P": r.p,
                                                          "Pperm": r.p_perm, "Pholm": getattr(r, "p_holm_family", np.nan)}))
    for set_key, sk in [(CONFIRMATORY, "Conf"), (LOCALISABLE, "Loc"), (EVALUABLE, "Eval")]:
        for role, rk in [("primary", ""), ("headroom_normalised", "Norm"), ("robust_excl_R0", "ExclRzero")]:
            for m, mk in [("info_nats_fm_adj", "Info"), ("dAP_stacked_fm_adj", "Stacked"),
                          ("info_frac_fm_adj", "Info"), ("dAPh_fm_adj", "Stacked")]:
                x = META[(META["set"] == set_key) & (META["ordering"] == "A_terrain_first") & (META["role"] == role)
                         & (META["metric"] == m)] if len(META) else META
                if len(x):
                    r = x.iloc[0]
                    macros.append(sc.latex_macros(f"Meta{sk}{rk}{mk}", {"K": int(r["k"]), "Est": r["estimate"], "Lo": r["ci_low"],
                                                                     "Hi": r["ci_high"], "P": r["p_one_sided_lt0"],
                                                                     "Isq": r["I2"], "Tau": r["tau2"]}))
    for m, mk in [("dAP_adr_legacy_fm", "Legacy"), ("dAP_gated_fm", "Gated"), ("dAP_stacked_fm", "Stacked"),
                  ("dAP_early_fm", "Early"), ("info_frac_fm", "InfoFrac")]:
        x = TM[(TM["set"] == CONFIRMATORY) & (TM["metric"] == m)] if len(TM) else TM
        if len(x):
            r = x.iloc[0]
            macros.append(sc.latex_macros(f"TopTierA{mk}", {"K": int(r["k"]), "Est": r["estimate"], "Lo": r["ci_low"],
                                                             "Hi": r["ci_high"], "P": r["p_two_sided"]}))
    for m, mk in [("dAP_adr_legacy_fm", "Legacy"), ("dAP_gated_fm", "Gated"), ("dAP_stacked_fm", "Stacked"),
                  ("dAP_early_fm", "Early"), ("info_frac_fm", "InfoFrac")]:
        x = TM[(TM["set"] == EVALUABLE) & (TM["metric"] == m)] if len(TM) else TM
        if len(x):
            r = x.iloc[0]
            macros.append(sc.latex_macros(f"TopEval{mk}", {"K": int(r["k"]), "Est": r["estimate"], "Lo": r["ci_low"],
                                                           "Hi": r["ci_high"], "P": r["p_two_sided"]}))
    macros.append(sc.latex_macros("Cities", {"Total": len(states), "Current": sum(v["current"] for v in info.values()),
                                              "Confirmatory": len(sets[CONFIRMATORY]),
                                              "Evaluable": len(sets[EVALUABLE]),
                                              "Localisable": len(sets[LOCALISABLE])}))
    open(os.path.join(d, "synthesis_macros.tex"), "w").write("\n".join(macros) + "\n")
    # ---- plain-language summary for the manuscript update --------------------------------------------------------
    L = [f"# Synthesis (pipeline {PIPELINE_VERSION}, pre-registration {h[:8]})", ""]
    if ap_.get("study_set"):
        L.append(f"Study set (pre-registration): {len(ap_['study_set'])} cities: {', '.join(ap_['study_set'])}")
        missing = [c for c in ap_["study_set"] if c not in states or not info.get(c, {}).get("current")]
        if missing:
            L.append(f"**NOT YET ANALYSED under this pre-registration: {', '.join(missing)}. Every pooled number below "
                     f"is provisional until they are.**")
    if stale:
        L.append(f"Not in any pooled set (computed under an older pre-registration, re-run them): {', '.join(stale)}")
    if outside:
        L.append(f"Not in any pooled set (outside the study set): {', '.join(outside)}")
    for k_, v_ in sets.items():
        L.append(f"- set '{k_}': {len(v_)} cities: {', '.join(sorted(v_)) or '-'}")
    L.append("")
    # v6.1: what the layer is, and which cities' numbers must not be read as findings
    if len(T1):
        L.append("## Read this first")
        for r in T1.itertuples():
            notes = []
            if getattr(r, "signal_type", None):
                notes.append(f"layer = {r.signal_type}")
            if not r.evaluable_social_layer:
                notes.append(f"NO EVALUABLE SOCIAL LAYER ({0 if pd.isna(r.mentions_primary) else int(r.mentions_primary)} located mentions): "
                             f"its social effects are noise")
            if not r.acquisition_complete:
                notes.append("ACQUISITION INCOMPLETE OR UNDER OLDER RULES: re-acquire before use")
            if isinstance(r.label_caveat, str) and r.label_caveat:
                notes.append(f"label caveat: {r.label_caveat}")
            if notes:
                L.append(f"- {r.city}: " + "; ".join(notes))
        L.append("- Verdicts are the pre-registered ones. 'reading' adds whether the whole 90% interval lies inside the "
                 "SESOI: an effect can be non-zero and still negligible.")
        L.append("- A pooled interval inside the SESOI is not evidence from every city: see the weights and "
                 "leave-one-out estimates in T11 before describing any pooled result.")
        L.append("")
    if len(META):
        for role in ("primary", "headroom_normalised", "robust_excl_R0"):
            x = META[(META["set"] == CONFIRMATORY) & (META["ordering"] == "A_terrain_first") & (META["role"] == role)]
            for r in x.itertuples():
                L.append(f"RQ3 pooled slope [{role}] {r.metric}: {r.estimate:+.4f} (95% CI {r.ci_low:+.4f} to {r.ci_high:+.4f}; "
                         f"one-sided p (H1: slope < 0)={r.p_one_sided_lt0:.4f}; k={r.k}; I2={r.I2:.2f}; tau2={r.tau2:.4g}; "
                         f"PI {r.pi_low:+.3f} to {r.pi_high:+.3f})")
    if len(MOD):
        L.append("")
        for r in MOD.itertuples():
            line = (f"RQ3 moderator [{r.analysis}] {r.outcome} ~ {r.moderator}: slope {r.slope:+.4f} (SE {r.slope_se:.4f}; "
                    f"KH p={r.p:.4f}; permutation p={r.p_perm:.4f}; k={r.k})")
            if r.analysis == "confirmatory":
                line += f"; Holm p across the {int(r.family_size)} confirmatory moderator tests={r.p_holm_family:.4f}"
                if isinstance(getattr(r, "most_influential_city", ""), str) and r.most_influential_city:
                    line += (f"; leave-one-out slope {r.loo_slope_min:+.4f} to {r.loo_slope_max:+.4f} "
                             f"(sign {'stable' if r.loo_sign_stable else 'NOT stable'}; most influential {r.most_influential_city}, "
                             f"slope without it {r.slope_without_it:+.4f})")
            L.append(line)
    if len(INFL):
        L.append("")
        for q, x in INFL.groupby("quantity", sort=False):
            x = x.sort_values("weight", ascending=False)
            top2 = x.head(2)
            L.append(f"Influence {q}: {', '.join(f'{c_} {w_:.0%}' for c_, w_ in zip(top2['city'], top2['weight']))} of the pooled weight; "
                     f"leave-one-out estimate from {x['loo_estimate'].min():+.4f} to {x['loo_estimate'].max():+.4f} "
                     f"(all cities {x['full_estimate'].iloc[0]:+.4f} [{x['full_ci_low'].iloc[0]:+.4f}, {x['full_ci_high'].iloc[0]:+.4f}])")
    if len(TM):
        L.append("")
        for r in TM[TM["set"].isin([CONFIRMATORY, EVALUABLE])].itertuples():
            L.append(f"RQ1 pooled top rung [{r.set}] {r.metric}: {r.estimate:+.4f} (95% CI {r.ci_low:+.4f} to {r.ci_high:+.4f}; k={r.k}; I2={r.I2:.2f})")
    if len(PC):
        L.append("")
        x = PC[(PC["ordering"] == "A_terrain_first") & (PC["role"] == "primary")]
        for r in x.itertuples():
            L.append(f"RQ2 {r.city} {r.metric}: slope {r.slope:+.4f} [{r.ci_low:+.4f}, {r.ci_high:+.4f}], one-sided p={r.p_one_sided:.4f}"
                     + (f", Holm p={r.holm_p_primary_family:.4f}" if np.isfinite(r.holm_p_primary_family) else " (not in the confirmatory family)"))
    if len(TOP):
        L.append("")
        for r in TOP.itertuples():
            L.append(f"RQ1 {r.city} {r.rung} {r.metric}: {r.estimate:+.4f} [{r.ci95_low:+.4f}, {r.ci95_high:+.4f}] -> {r.verdict}"
                     + (f" | reading: {r.reading}" if r.reading != r.verdict else "")
                     + ("" if r.evaluable_social_layer else " | no evaluable social layer"))
    if len(PL):
        L.append("")
        for r in PL.itertuples():
            L.append(f"Placebo {r.city} {r.metric}: real slope {r.real_slope:+.4f} vs population-density slope {r.placebo_slope:+.4f}; "
                     f"Spearman(social, population) {r.spearman_social_population:.2f}"
                     + (f"; social gain with population controlled at top rung {r.control_top_estimate:+.4f} "
                        f"[{r.control_top_ci95_low:+.4f}, {r.control_top_ci95_high:+.4f}] {r.control_top_verdict}"
                        if "control_top_estimate" in PL.columns and pd.notna(getattr(r, "control_top_estimate", np.nan)) else ""))
    open(os.path.join(d, "RESULTS_SUMMARY.md"), "w").write("\n".join(L) + "\n")
    log("(all)", "synthesis", "ok", f"{len(states)} cities ({sum(v['current'] for v in info.values())} under the current "
                                    f"pre-registration); confirmatory k={len(sets[CONFIRMATORY])}, evaluable k={len(sets[EVALUABLE])}, "
                                    f"localisable k={len(sets[LOCALISABLE])} -> {SYN_DIR}/")
    return META
